const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Plugins.Browser,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X
	];
};
self.C3_JsPropNameTable = [
	{fundo01: 0},
	{PlanoDeFundoEmBlocos: 0},
	{bot_iniciar: 0},
	{bot_sair: 0},
	{bot_opcoes: 0},
	{txt_iniciar: 0},
	{txt_opcoes: 0},
	{txt_sair: 0},
	{titulo_: 0},
	{fundo02: 0},
	{ico_musica: 0},
	{ico_som: 0},
	{Mouse: 0},
	{Toque: 0},
	{Teclado: 0},
	{fundo03: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Áudio: 0},
	{CentrarEm: 0},
	{camera01: 0},
	{click01: 0},
	{dinheiro_txt: 0},
	{dinheiro_vl: 0},
	{popularidade_txt: 0},
	{popularidade_vl: 0},
	{trabalhadores_txt: 0},
	{trabalhadores_vl: 0},
	{Navegador: 0},
	{bot_voz: 0},
	{txt_voz: 0},
	{ico_voz: 0},
	{teste: 0},
	{musica: 0},
	{som: 0},
	{voz: 0},
	{dinheiro: 0},
	{popularidade: 0},
	{trabalhadores: 0}
];

self.InstanceType = {
	fundo01: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	bot_iniciar: class extends self.ISpriteInstance {},
	bot_sair: class extends self.ISpriteInstance {},
	bot_opcoes: class extends self.ISpriteInstance {},
	txt_iniciar: class extends self.ITextInstance {},
	txt_opcoes: class extends self.ITextInstance {},
	txt_sair: class extends self.ITextInstance {},
	titulo_: class extends self.ISpriteInstance {},
	fundo02: class extends self.ISpriteInstance {},
	ico_musica: class extends self.ISpriteInstance {},
	ico_som: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	fundo03: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	camera01: class extends self.ISpriteInstance {},
	click01: class extends self.ISpriteInstance {},
	dinheiro_txt: class extends self.ITextInstance {},
	dinheiro_vl: class extends self.ITextInstance {},
	popularidade_txt: class extends self.ITextInstance {},
	popularidade_vl: class extends self.ITextInstance {},
	trabalhadores_txt: class extends self.ITextInstance {},
	trabalhadores_vl: class extends self.ITextInstance {},
	Navegador: class extends self.IInstance {},
	bot_voz: class extends self.ISpriteInstance {},
	txt_voz: class extends self.ITextInstance {},
	ico_voz: class extends self.ISpriteInstance {},
	teste: class extends self.ITextInstance {}
}